---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orderservice-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: orderservice-staging
  labels:
    app: orderservice-staging
spec:
  containers:
    - image: ubuntu
      command:
        - "sleep"
        - "604800"
      imagePullPolicy: IfNotPresent
      name: staging
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: 'orderservice-pvc'
  restartPolicy: Always