
openapi: 3.0.2
info:
  description: API for managing Currency resources.
  version: 0.0.1
  title: Curerency API
servers:
- url: "{SERVER_URL}/currencyservice"
security:
  - ApiKeyAuth: [] 
paths:
  /currencies:
    get:
      summary: List 'Currency' objects.
      description: Retrieve a list of 'Currency' objects from the server.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Currencies'    
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: apikey
      in: query
  schemas:
    Currencies:
      type: object
      properties:
        currencycodes:
          type: array
          items:
            type: string